---
- hosts: local
  gather_facts: yes
  vars_files:
    - /home/nms/ansible/keys.yml
  tasks:
    - name: Change instance state
#      local_action: ec2
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        instance_tags:
          Name: Demo
