---
- hosts: local
  gather_facts: yes
  vars_files:
    - /home/nms/ansible/keys.yml
  tasks:
    - name: Get instance details
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: Demo
      register: ec2_facts
    - name: Change instance state
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        instance_ids: "{{item.instance_id}}"
      with_items: "{{ ec2_facts.instances}}"
#
