---
- hosts: app1
  become: true
  tasks:
   - name: Creating user
     user:
      name: "{{ item }}"
     with_items:
      - kahan
      - dev
   - name: Creating directory
     file:
      dest: "/home/{{ item.0 }}/{{ item.1 }}"
      owner: "{{ item.0 }}"
      group: "{{ item.0 }}"
      state: directory
     with_nested:
       - [ kahan, dev ]
       - [ photos, movies ]    
   
