- hosts: all
  gather_facts: true
  vars:
    src_path: "/home/nms/test.txt"
    dest_path: "/home/nms/ansible/test"
  tasks:
  - name: copy from servers to jmp host
    fetch:
      src: "{{ src_path }}"
      dest: "{{ dest_path }}/{{ inventory_hostname }}"
      flat: yes
    register: file_cp
    ignore_errors: yes
  - name: Delete src
    file:
      path: "{{ src_path }}"
      state: absent
    when: file_cp.changed
  - name: find copied files in dest
    find:
      paths: /home/nms/ansible/test
      file_type: file
    register: result
    delegate_to: localhost
  - debug: var=item.path
    with_items: "{{ result.files }}"  
  - name: Send emails with files
    mail:
     host: smtp.gmail.com
     port: 587
     username: nmadhunms@gmail.com 
     password: nnmadhus17nms
     to: nmadhunms@gmail.com
     subject: XML Inventory from "{{ item.path | basename }}" 
     body: XML Inventory from "{{ item.path | basename }}"
     attach:
       - "{{ item.path }}"
    with_items: "{{ result.files }}"
    delegate_to: localhost

 # - name: send email
 #   shell: 
 #         -"/home/nms/ansible/test/mail.sh"
