---
- hosts: win
  gather_facts: false
  tasks:
  - name: Stop service
    win_service:
      name: spooler
      state: stopped
    register: service_stopped
  - name: Rename Folder
    win_shell: Rename-Item C:\Users\test.txt test1.txt
    when: service_stopped.changed
    register: folder_renamed
  - name: Start service
    win_service:
      name: spooler
      state: started
    when: folder_renamed.changed
