---
- hosts: app1
  gather_facts: false
  become: true
  vars_prompt:
    - name: check_cert
      prompt: "what is path?"
  roles:
      - /home/nms/ansible/roles/installscxagent
      - /home/nms/ansible/roles/checkscxstatus
      - /home/nms/ansible/roles/certscxagent
  



