- hosts: localhost
  tasks:
  - name: Send emails with files
    mail:
     host: smtp.gmail.com
     port: 587
     username: 
     password: s
     to: 
     subject: XML Inventory from "{{ item | basename }}"
     body: XML Inventory from "{{ item | basename }}"
     attach:
       - "{{ item }}"
    with_fileglob: 
       - "/home/nms/ansible/test/*"

